### Product-svc
POST http://localhost:8080/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 1000,
    "description": "Product 1 description",
    "category": "Category 1",
    "quantity": 10
}

### Product-search-svc
GET http://localhost:8081/products/3098b596-6129-4297-947e-42ce5620e0a1