version: '3.8'

services:
  pastebin_pg:
    image: postgres:14.5
    container_name: pastebin_pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metadata
    ports:
      - "5435:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    ports:
      - 29092:29092

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es
    ports:
      # The port 9200 is used for external communication with the Elasticsearch cluster: indexing and querying data
      - 9200:9200
      # port 9300 is used for internal communication between nodes in the cluster
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"

  kibana:
    container_name: kb
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    ports:
      - 5601:5601