version: '3.8'
services:
  postgres1:
    image: postgres:14.5
    container_name: postgres1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard1
    ports:
      - "5434:5432"

  postgres2:
    image: postgres:14.5
    container_name: postgres2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard2
    ports:
      - "5435:5432"

  # app:
  #   build:
  #     context: ./user-svc
  #     dockerfile: Dockerfile
  #   container_name: sharding_app