### Health check
GET http://localhost/health


### Get products
GET http://localhost/products


### Get product by id
GET http://localhost/products/1

### Create product
POST http://localhost/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100
}


### Update product
PUT http://localhost:8080/products/1
Content-Type: application/json

{
    "price": 101
}