version: '3.9'

services:
  db_master:
    image: mysql:8.0
    container_name: db_master
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./config/my-master.cnf:/etc/mysql/my.cnf
    networks:
      - mysql_net

  db_replica_1:
    image: mysql:8.0
    container_name: db_replica_1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    volumes:
      - ./config/my-replica.cnf:/etc/mysql/my.cnf
    depends_on:
      - db_master
    networks:
      - mysql_net

  db_bkp:
    # image: mysql:8.0
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: db_bkp
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./backup-scripts/daily_to_current_vm.sh:/scripts/daily_to_current_vm.sh
      - ./backup-scripts/weekly_to_current_vm.sh:/scripts/weekly_to_current_vm.sh
    networks:
      - mysql_net

networks:
  mysql_net: