// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	hello "client-svc/hello"

	mock "github.com/stretchr/testify/mock"
)

// HelloServiceClient is an autogenerated mock type for the HelloServiceClient type
type HelloServiceClient struct {
	mock.Mock
}

// HelloSomeone provides a mock function with given fields: ctx, in, opts
func (_m *HelloServiceClient) HelloSomeone(ctx context.Context, in *hello.HelloRequest, opts ...grpc.CallOption) (*hello.HelloResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *hello.HelloResponse
	if rf, ok := ret.Get(0).(func(context.Context, *hello.HelloRequest, ...grpc.CallOption) *hello.HelloResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hello.HelloResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *hello.HelloRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHelloServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewHelloServiceClient creates a new instance of HelloServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHelloServiceClient(t mockConstructorTestingTNewHelloServiceClient) *HelloServiceClient {
	mock := &HelloServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
