// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	random "client-svc/random"
)

// RandomServiceClient is an autogenerated mock type for the RandomServiceClient type
type RandomServiceClient struct {
	mock.Mock
}

// Random provides a mock function with given fields: ctx, in, opts
func (_m *RandomServiceClient) Random(ctx context.Context, in *random.RandomRequest, opts ...grpc.CallOption) (*random.RandomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *random.RandomResponse
	if rf, ok := ret.Get(0).(func(context.Context, *random.RandomRequest, ...grpc.CallOption) *random.RandomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*random.RandomResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *random.RandomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRandomServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewRandomServiceClient creates a new instance of RandomServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRandomServiceClient(t mockConstructorTestingTNewRandomServiceClient) *RandomServiceClient {
	mock := &RandomServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
