// Code generated by protoc-gen-go. DO NOT EDIT.
// source: random.proto

/*
Package random is a generated protocol buffer package.

It is generated from these files:

	random.proto

It has these top-level messages:

	RandomRequest
	RandomResponse
*/
package random

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RandomRequest struct {
	From int32 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   int32 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
}

func (m *RandomRequest) Reset()                    { *m = RandomRequest{} }
func (m *RandomRequest) String() string            { return proto.CompactTextString(m) }
func (*RandomRequest) ProtoMessage()               {}
func (*RandomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RandomRequest) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *RandomRequest) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type RandomResponse struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *RandomResponse) Reset()                    { *m = RandomResponse{} }
func (m *RandomResponse) String() string            { return proto.CompactTextString(m) }
func (*RandomResponse) ProtoMessage()               {}
func (*RandomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RandomResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*RandomRequest)(nil), "RandomRequest")
	proto.RegisterType((*RandomResponse)(nil), "RandomResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RandomService service

type RandomServiceClient interface {
	Random(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*RandomResponse, error)
}

type randomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRandomServiceClient(cc *grpc.ClientConn) RandomServiceClient {
	return &randomServiceClient{cc}
}

func (c *randomServiceClient) Random(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*RandomResponse, error) {
	out := new(RandomResponse)
	err := grpc.Invoke(ctx, "/RandomService/Random", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RandomService service

type RandomServiceServer interface {
	Random(context.Context, *RandomRequest) (*RandomResponse, error)
}

func RegisterRandomServiceServer(s *grpc.Server, srv RandomServiceServer) {
	s.RegisterService(&_RandomService_serviceDesc, srv)
}

func _RandomService_Random_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomServiceServer).Random(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RandomService/Random",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomServiceServer).Random(ctx, req.(*RandomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RandomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RandomService",
	HandlerType: (*RandomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Random",
			Handler:    _RandomService_Random_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "random.proto",
}

func init() { proto.RegisterFile("random.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0xcc, 0x4b,
	0xc9, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe6, 0xe2, 0x0d, 0x02, 0xf3, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xd2, 0x8a, 0xf2, 0x73, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x3e, 0x2e, 0xa6, 0x92, 0x7c, 0x09, 0x26, 0xb0,
	0x08, 0x53, 0x49, 0xbe, 0x92, 0x06, 0x17, 0x1f, 0x4c, 0x53, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa,
	0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x09, 0x54, 0x1f, 0x94, 0x67, 0x64, 0x05,
	0x33, 0x3e, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48, 0x93, 0x8b, 0x0d, 0x22, 0x20, 0xc4,
	0xa7, 0x87, 0x62, 0xb1, 0x14, 0xbf, 0x1e, 0xaa, 0x99, 0x49, 0x6c, 0x60, 0x17, 0x1a, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x09, 0x69, 0x84, 0xf1, 0xb1, 0x00, 0x00, 0x00,
}
