version: '3.9'

services:
  chat_redis:
    container_name: chat_redis
    image: redis:6.2.5
    ports:
      - "6378:6379"

  websocket_app_1:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: websocket_app_1
    environment:
      - REDIS_HOST=chat_redis
      - REDIS_PORT=6379
    ports:
      - 8081:8080

  websocket_app_2:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: websocket_app_2
    environment:
      - REDIS_HOST=chat_redis
      - REDIS_PORT=6379
    ports:
      - 8082:8080

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 8080:8080