apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-app-deployment
  labels:
    app: my-hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-hello-app
  template:
    metadata:
      labels:
        app: my-hello-app
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: my-hello-app
        image: vnscriptkid/my-hello-app:v1
        imagePullPolicy: IfNotPresent # IfNotPresent (local->dockerhub: default) Always (dockerhub), Never (local)
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: my-hello-app-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-hello-app
---
apiVersion: v1
kind: Service
metadata:
  name: my-hello-app-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: my-hello-app