### Send notification
POST http://localhost:8080/send-notification
Content-Type: application/json

{
    "recipient": "linhgmail.com",
    "template_name": "welcome_email",
    "channel": "email",
    "priority": 1,
    "data": {
        "UserName": "vnscriptkid",
        "PlatformName": "github"
    }
}