version: '3.8'
services:
  app:
    build: ./app
    container_name: clustering_app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ./app:/app